### ISSUE TITLE
new error "cannot create a file when that file already exists"

### ISSUE THREAD

**Issue by Datura123** [rm-NoobInCoding/UnrealReZen#23]
Thank @rm-NoobInCoding for fix B03, but it appeared another error the new version B04

![Untitled 5677- Copy](https://github.com/rm-NoobInCoding/UnrealUnZen/assets/65519230/9975c8b9-702f-4091-887d-df3b81d19dca)

**Comment by binlv2012** [comment]
In the old version B03, this error is not encountered

**Comment by rm-NoobInCoding** [comment]
Please click on Details and send its text

**Comment by binlv2012** [comment]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.IOException: Cannot create a file when that file already exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateCore(SafeFileHandle fileHandle, String mapName, HandleInheritability inheritability, MemoryMappedFileSecurity memoryMappedFileSecurity, MemoryMappedFileAccess access, MemoryMappedFileOptions options, Int64 capacity)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateFromFile(String path, FileMode mode, String mapName, Int64 capacity, MemoryMappedFileAccess access)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateFromFile(String path, FileMode mode, String mapName)
   at UEcastocLib.Packer.PackFilesToUcas(List`1 files, Manifest m, String dir, String outFilename, String compression) in C:\Users\PCMOD\source\repos\rm-NoobInCoding\UnrealUnZen\UnrealUnZen\UEcastocLib\Pack.cs:line 133
   at UEcastocLib.Packer.PackToCasToc(String dir, Manifest m, String outFilename, String compression, Byte[] aes) in C:\Users\PCMOD\source\repos\rm-NoobInCoding\UnrealUnZen\UnrealUnZen\UEcastocLib\Pack.cs:line 422
   at UEcastocLib.Packer.PackGameFiles(String dirPath, Manifest manifest, String outFile, String compressionMethod, String AESKey) in C:\Users\PCMOD\source\repos\rm-NoobInCoding\UnrealUnZen\UnrealUnZen\UEcastocLib\Pack.cs:line 48
   at UnrealUnZen.MainTool.RepackBTN_Click(Object sender, EventArgs e) in C:\Users\PCMOD\source\repos\rm-NoobInCoding\UnrealUnZen\UnrealUnZen\MainTool.cs:line 93
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
UnrealUnZen
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/DL2/UnrealUnZen-B04%20(1)/UnrealUnZen.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9093.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Microsoft.WindowsAPICodePack.Shell
    Assembly Version: 1.1.5.0
    Win32 Version: 1.1.5.0
    CodeBase: file:///D:/DL2/UnrealUnZen-B04%20(1)/Microsoft.WindowsAPICodePack.Shell.DLL
----------------------------------------
Microsoft.WindowsAPICodePack
    Assembly Version: 1.1.5.0
    Win32 Version: 1.1.5.0
    CodeBase: file:///D:/DL2/UnrealUnZen-B04%20(1)/Microsoft.WindowsAPICodePack.DLL
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by binlv2012** [comment]
I tried deleting the file with the same name and it worked

If there are 2 files with the same name in that common folder, it will encounter an error, for example: DroidSansMono.uasset

"Engine/Content/EngineFonts/Faces/DroidSansMono.uasset",
"Engine/Content/EngineFonts/DroidSansMono.uasset"

**Comment by KulaGGin** [comment]
> I tried deleting the file with the same name and it worked
> 
> If there are 2 files with the same name in that common folder, it will encounter an error, for example: DroidSansMono.uasset
> 
> "Engine/Content/EngineFonts/Faces/DroidSansMono.uasset", "Engine/Content/EngineFonts/DroidSansMono.uasset"

This is definitely a bug. It's totally possible to have a lot of files with the same name in the same package. For example:
![UnrealUnZen_SLQkDeMzxB](https://github.com/rm-NoobInCoding/UnrealUnZen/assets/16989713/0679b94e-eb47-4c27-8f8c-b8e0848b80d4)

And there is no deleting the files for me. I just checked, I have 5980 duplicated files.

**Comment by KulaGGin** [comment]
This issue is happening because of the line:

```CSharp
MemoryMappedFile = MemoryMappedFile.CreateFromFile(pathToread, FileMode.Open, Path.GetFileNameWithoutExtension(pathToread));
```
In [pack.cs#L133](https://github.com/rm-NoobInCoding/UnrealUnZen/blob/45736b546cce979b1c4a68346bbcabdca1cd176f/UnrealUnZen/UEcastocLib/pack.cs#L133). This is happening is because you're calling [MemoryMappedFile.CreateFromFile](https://learn.microsoft.com/en-us/dotnet/api/system.io.memorymappedfiles.memorymappedfile.createfromfile?view=net-7.0#system-io-memorymappedfiles-memorymappedfile-createfromfile\(system-string-system-io-filemode-system-string\)) overload with mapName: you're creating a MemoryMappedFile and assigning it a mapName for a file. And so you can't have a file with the same mapName loaded twice in the memory. The quick fix is to use a different overload and just not pass the `mapName` to `CreateFromFile` function:

```CSharp
MemoryMappedFile = MemoryMappedFile.CreateFromFile(pathToread, FileMode.Open);
```

This fixes the bug: I packed 51000 files with 5980 files with duplicated names. But why are you even using MemoryMappedFile? MemoryMappedFile is made for big heavy files, so the file can be shared across running processes and wouldn't have to be loaded twice into each process. It's useless for this kind of a use case where you have one process just iterating over a bunch of files, reading them into memory, then archiving them and then forgetting about them, all without using them even twice around the program. In fact, it's using more memory than a simple Stream, because it's a much more complex type than a simple Stream. Just use [File.Open](https://learn.microsoft.com/en-us/dotnet/api/system.io.file.open?view=net-8.0).

**Comment by KulaGGin** [comment]
Created pull request with the fix. And before the official release is created, here's the zip of program with the fix: [UnrealUnZen.zip](https://github.com/rm-NoobInCoding/UnrealUnZen/files/13466445/UnrealUnZen.zip)

**Comment by binlv2012** [comment]
> Created pull request with the fix. And before the official release is created, here's the zip of program with the fix: [UnrealUnZen.zip](https://github.com/rm-NoobInCoding/UnrealUnZen/files/13466445/UnrealUnZen.zip)

sorry but, it can't repack over 2GB file
![image](https://github.com/rm-NoobInCoding/UnrealUnZen/assets/65519230/6e581199-5b62-46ce-b58c-4b176d4d5f49)

**Comment by KulaGGin** [comment]
> > Created pull request with the fix. And before the official release is created, here's the zip of program with the fix: [UnrealUnZen.zip](https://github.com/rm-NoobInCoding/UnrealUnZen/files/13466445/UnrealUnZen.zip)
> 
> sorry but, it can't repack over 2GB file ![image](https://private-user-images.githubusercontent.com/65519230/285652931-6e581199-5b62-46ce-b58c-4b176d4d5f49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwMDY5MTYsIm5iZiI6MTcwMTAwNjYxNiwicGF0aCI6Ii82NTUxOTIzMC8yODU2NTI5MzEtNmU1ODExOTktNWI2Mi00NmNlLWI1OGMtNGIxNzZkNGQ1ZjQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDEzNTAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNmFjOGE5NzZiNDg0ZjcxM2MxZmY1N2NkZTQ5MmM4NDk0YTUzMThiNzJiMzRiOGI4MjMxZWZiMTRmYTJkYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.feXMhmWdhRjR_XBJcaRBxdooOQXyv5jKkbvtosqhulo)

Right. That's why MemoryMappedFile was used. Try this one then: 
[UnrealUnZen.zip](https://github.com/rm-NoobInCoding/UnrealUnZen/files/13466966/UnrealUnZen.zip)

**Comment by binlv2012** [comment]
I tried this, it still doesn't work

> > sorry but, it can't repack over 2GB file
> 
> Right. That's why MemoryMappedFile was used. Try this one then: [UnrealUnZen.zip](https://github.com/rm-NoobInCoding/UnrealUnZen/files/13466966/UnrealUnZen.zip)

I tried this, it still doesn't work. can't repack over 2GB file

**Comment by KulaGGin** [comment]
> I tried this, it still doesn't work. can't repack over 2GB file

I think I might have zipped this last version before I built the solution after going back one commit where there is no issue with over 2 GB files. That's my bad.

Try again: [UnrealUnZen.zip](https://github.com/rm-NoobInCoding/UnrealUnZen/files/13467289/UnrealUnZen.zip)

Yesterday I unpacked and then packed back two 11 GB packages after fixing this problem with "cannot create a file when that file already exists".

**Comment by binlv2012** [comment]
> 
> I think I might have zipped this last version before I built the solution after going back one commit where there is no issue with over 2 GB files. That's my bad.
> 
> Try again: [UnrealUnZen.zip](https://github.com/rm-NoobInCoding/UnrealUnZen/files/13467289/UnrealUnZen.zip)
> 
> Yesterday I unpacked and then packed back two 11 GB packages after fixing this problem with "cannot create a file when that file already exists".

Do you use repack with manifest.json?

**Comment by binlv2012** [comment]
> 
> I think I might have zipped this last version before I built the solution after going back one commit where there is no issue with over 2 GB files. That's my bad.
> 
> Try again: [UnrealUnZen.zip](https://github.com/rm-NoobInCoding/UnrealUnZen/files/13467289/UnrealUnZen.zip)
> 
> Yesterday I unpacked and then packed back two 11 GB packages after fixing this problem with "cannot create a file when that file already exists".

**Unfortunately I can't create files for my game:**

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.IOException: The file is too long. This operation is currently limited to supporting files less than 2 gigabytes in size.
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at UEcastocLib.Packer.PackToCasToc(String dir, Manifest m, String outFilename, String compression, Byte[] aes) in D:\Projects\Reversing\UE4\UnrealUnZen\UnrealUnZen\UEcastocLib\Pack.cs:line 424
   at UEcastocLib.Packer.PackGameFiles(String dirPath, Manifest manifest, String outFile, String compressionMethod, String AESKey) in D:\Projects\Reversing\UE4\UnrealUnZen\UnrealUnZen\UEcastocLib\Pack.cs:line 48
   at UnrealUnZen.MainTool.RepackBTN_Click(Object sender, EventArgs e) in D:\Projects\Reversing\UE4\UnrealUnZen\UnrealUnZen\MainTool.cs:line 93
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
UnrealUnZen
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/DL2/UnrealUnZen%20(1)/UnrealUnZen.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9093.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.3.27908
    CodeBase: file:///D:/DL2/UnrealUnZen%20(1)/Newtonsoft.Json.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Microsoft.WindowsAPICodePack.Shell
    Assembly Version: 1.1.5.0
    Win32 Version: 1.1.5.0
    CodeBase: file:///D:/DL2/UnrealUnZen%20(1)/Microsoft.WindowsAPICodePack.Shell.DLL
----------------------------------------
Microsoft.WindowsAPICodePack
    Assembly Version: 1.1.5.0
    Win32 Version: 1.1.5.0
    CodeBase: file:///D:/DL2/UnrealUnZen%20(1)/Microsoft.WindowsAPICodePack.DLL
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by xjgames** [comment]
> > 我尝试了这个，仍然不起作用。无法重新打包超过 2GB 的文件
> 
> 我想在返回一次提交（其中超过 2 GB 文件没有问题）之后构建解决方案之前，我可能已经压缩了最后一个版本。那是我的不好。
> 
> 再试一次：[UnrealUnZen.zip](https://github.com/rm-NoobInCoding/UnrealUnZen/files/13467289/UnrealUnZen.zip)
> 
> 昨天，在解决“当文件已存在时无法创建文件”的问题后，我解压并打包了两个 11 GB 的包。

cannot repack over 2 GB file

**Comment by binlv2012** [comment]
> Ok, I've now implemented some fixes for the problems with packing more than 2 GB files. The previous versions I posted only included the fix for "cannot create a file when that file already exists" error.
> 
> Try it out and let me know if it works: [UnrealUnZen.zip](https://github.com/rm-NoobInCoding/UnrealUnZen/files/13479533/UnrealUnZen.zip)
> 
> I've just now packed 2.5 GB .ucas with encryption enabled this time.

thank you, it worked!
![image](https://github.com/rm-NoobInCoding/UnrealUnZen/assets/65519230/b689d417-52e7-48e5-b95a-f0807975f96e)

**Comment by xjgames** [comment]
![1701169522822](https://github.com/rm-NoobInCoding/UnrealUnZen/assets/132032603/bce9b93e-57d4-4a9a-92f8-1da4d3369c8d)
The packed utoc cannot be opened

**Comment by rm-NoobInCoding** [comment]
I don't think you did it right
A toc file should not be 2.94 GB :|

**Comment by rm-NoobInCoding** [comment]
Did you define AES KEY in FModel?

**Comment by xjgames** [comment]
![9683d4e51d17ba78699ad35897a48eb](https://github.com/rm-NoobInCoding/UnrealUnZen/assets/132032603/9d9f4867-90b6-44e0-bb76-06b2623d6a8b)
yes

**Comment by xjgames** [comment]
Game Name  Dead Island 2
AES KEY =0x014AEC0148FBDEE9640633AAB67521AAB4E1083A98F76FF33DDCF78DAD05BE66

**Comment by rm-NoobInCoding** [comment]
Can you send repacked Toc file?

**Comment by xjgames** [comment]
[toc.zip](https://github.com/rm-NoobInCoding/UnrealUnZen/files/13487942/toc.zip)
